version: 2
jobs: 
  build:
    working_directory:~/tmp
    docker:
      -image: circleci/node:7
    steps: 
      -checkout
      -run: npm install
      -run: npm test
      -restore_cache:
        keys:
          - source-vl-{{ .Branch}}-{{ .Revision}}
          - source-vl-{{ .Branch}}-
          - source-vl-

        -checkout

        -save-cache:
          key: source-vl-{{ .Branch}}-{{ .Revision}}
          paths:
            - ".git"
